---
name: Elza Abdrakhmanova # ваше имя
job: QA Engineer
level: junior
email: tale.teller11@gmail.com
description: |
  Окончила курсы в автошколе, у меня есть права, но я боюсь водить машину
  Обожаю дарить подарки, это гораздо интереснее, чем их получать
  В детстве любила см документальные фильмы
  В свободное время читаю художественную или обучающую литературу
  Окончила школу искусств
  Не люблю свой день рождения
  Не смотрю телевизор
skills: # список навыков в виде списка, напишите что-то свое
  - функциональное тестирование
  - слепая печать, в процессе
  - хорошие коммуникативные навыки
  - работа в команде 
